Parameters:
  HostedZoneId:
    Description: select your hosted zone id from here
    Type: AWS::Route53::HostedZone::Id
  # SSLCertificat:
  #   Description: enter the ARN of SSL Certificate
  #   Type: String
  ALBDNSName:
    Description: Enter the ALB DNS same Here 
    Type: String
  DNSName:
    Description: Enter your Domain Name Here
    Type: String
    Default: shabeeb.ml
Resources:
#ssl certificate creation for cloudfront
  SSLCertificate: 
    Type: "AWS::CertificateManager::Certificate"
    Properties: 
      DomainName: !Ref DNSName
      ValidationMethod: DNS
  #CLOUDFRONT DISTRIBUTION
  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DNSName
        Origins:
          - DomainName: !Ref 'ALBDNSName'
            Id: !Ref 'ALBDNSName'
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: http-only
              OriginKeepaliveTimeout: '5'
              OriginReadTimeout: '30'
              OriginSSLProtocols:
                - TLSv1.2
        Enabled: true
        HttpVersion: 'http2'
        DefaultCacheBehavior:
          ForwardedValues:
              QueryString: false
          ViewerProtocolPolicy: redirect-to-https
          TargetOriginId: !Ref 'ALBDNSName'
          AllowedMethods:
            - GET
            - HEAD
            - DELETE
            - OPTIONS
            - PATCH
            - POST
            - PUT
        PriceClass: 'PriceClass_All'
        ViewerCertificate:
          AcmCertificateArn: !Ref 'SSLCertificate'
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only
  route53RSGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets: 
      - Name: !Ref DNSName
        Type: A
        AliasTarget:
          DNSName: !GetAtt CloudFrontDistribution.DomainName
          HostedZoneId: 'Z2FDTNDATAQYW2'
  
