AWSTemplateFormatVersion: '2010-09-09'
Description: ACM DNS Validation template (20180828)
Parameters:
  DomainName:
    Description: FQDN of the certificate
    Type: String
    Default: ''
Resources:
  ACMCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub '*.${DomainName}'
      SubjectAlternativeNames:
        - !Ref 'DomainName'
      DomainValidationOptions:
        - DomainName: !Sub '*.${DomainName}'
          ValidationDomain: !Ref 'DomainName'
      Tags:
        - Key: name
          Value: !Sub '${DomainName}-20180828'
      ValidationMethod: DNS
