Description: "IAM role for updating contents on S3"
# iam-role-specific-s3-operation.yaml
Parameters:
  S3BucketName:
    Description: S3 Bucket name
    Type: String
    Default: test-s3-bucket
  S3accessRoleName:
    Description: IAM role name
    Type: String
    Default: iam-role-specific-s3-operation
  SwitchIamUserArn:
    Description: Switch IAMUser(arn)
    Type: String
    Default: arn:aws:iam::123456789012:user/iam-user-name
Resources:
  IamRoleS3access:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: 
            Action: sts:AssumeRole
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: 'true'
      Policies:
        - PolicyName: S3accessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListAllMyBuckets
                  - s3:GetBucketLocation
                Resource:
                  - arn:aws:s3:::*
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !Sub 'arn:aws:s3:::${S3BucketName}/*'
                  - !Sub 'arn:aws:s3:::${S3BucketName}'
              - Effect: Deny
                Action:
                  - s3:PutBucket*
                  - s3:PutObjectAcl
                  - s3:PutObjectVersionAcl
                Resource:
                  - arn:aws:s3:::*
      RoleName: !Ref 'S3accessRoleName'
Outputs:
  IamRoleS3accessArn:
    Value: !GetAtt IamRoleS3access.Arn


